language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t diegochacon/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true diegochacon/docker-react npm run test